source 'https://github.com/CocoaPods/Specs.git'
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, ‘8.0’
inhibit_all_warnings!
target 'GroupPhotos’ do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'ZLPhotoBrowser’
  # Pods for GroupShot

end
